[alembic]
script_location = alembic
sqlalchemy.url = postgresql://neondb_owner:npg_In3fFgkR5KTa@ep-wandering-night-a4zi29rn-pooler.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require

[post_write_hooks]

[logging]
default_handler = console
log_file = alembic.log

[logger_root]
level = INFO
handlers = console

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
